import os
import subprocess
import logging
import json
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel
import requests

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("render-service")

app = FastAPI(title="Video Render Service")

# Resolve storage directories
STORAGE_DIR = os.getenv("STORAGE_DIR", os.path.abspath(os.path.join(os.path.dirname(__file__), "../../storage")))
OUTPUT_DIR = os.path.join(STORAGE_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

active_processes = {}
cancelled_jobs = set()

class RenderRequest(BaseModel):
    synced_video_path: str
    audio_path: str
    alignment_path: str = None
    job_id: str
    watermark_text: str = ""
    caption_style: str = "active_word"
    font_name: str = "Arial"
    font_size: float = 24.0
    bgm_path: str | None = None
    bgm_volume: float = 0.1

class RenderResponse(BaseModel):
    status: str
    output_video_path: str
    details: str

def time_to_ass(seconds: float) -> str:
    """Formats float seconds into ASS H:MM:SS.CC timestamp."""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds - int(seconds)) * 100))
    if centiseconds == 100:
        secs += 1
        centiseconds = 0
    return f"{hours:d}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"

def generate_ass_file(alignment_path: str, output_ass_path: str, caption_style: str, font_name: str, font_size: float, video_width: int, video_height: int):
    """Compiles word-by-word timestamps into a styled ASS file with dynamic aspect-ratio scaling."""
    with open(alignment_path, "r", encoding="utf-8") as f:
        words = json.load(f)
        
    primary_color = "&H00FFFFFF&"      # White
    secondary_color = "&H0000FFFF&"    # Default Yellow secondary
    outline_color = "&H00000000&"      # Black outline
    back_color = "&H80000000&"         # Semitransparent shadow
    bold = "-1"
    border_style = "1"
    
    # Use standard 720 reference height to calculate dynamic width based on aspect ratio
    play_res_y = 720
    play_res_x = int(720 * (video_width / video_height))
    
    # Scale variables from standard 480 height to 720 reference height
    scale_factor = 720 / 480
    scaled_font_size = font_size * scale_factor
    
    outline = str(3.0 * scale_factor)
    shadow = "0.0"
    alignment = "2"                    # Centered Bottom
    margin_v = str(int(70 * scale_factor))
    highlight_tag = "{\\c&H00FFFF&}"   # Yellow highlight (ASS color syntax: &HBBGGRR&)
    
    if caption_style == "minimal_white":
        outline = "0.0"
        shadow = str(1.0 * scale_factor)
        margin_v = str(int(50 * scale_factor))
        highlight_tag = ""
    elif caption_style == "bold_outlined":
        outline = str(4.0 * scale_factor)
        shadow = str(1.0 * scale_factor)
        margin_v = str(int(80 * scale_factor))
        highlight_tag = "{\\c&HFF00FF&}"   # Pink highlight (BGR: Red + Blue)
    elif caption_style == "hormozi_pop":
        if font_name == "Arial": font_name = "Impact"
        bold = "1"
        outline = str(6.0 * scale_factor)
        shadow = str(2.0 * scale_factor)
        margin_v = str(int(100 * scale_factor))
        highlight_tag = ""
    elif caption_style == "karaoke_box":
        border_style = "3"
        outline_color = "&H90000000&"
        back_color = "&HD0000000&"
        outline = "0.0"
        shadow = "0.0"
        margin_v = str(int(60 * scale_factor))
        highlight_tag = "{\\c&H00FFFF&}"
    elif caption_style == "neon_glow":
        bold = "-1"
        outline_color = "&H00FFFF00&"       # Cyan glow outline
        outline = str(3.0 * scale_factor)
        shadow = "0.0"                      # No shadow to avoid duplicate caption illusion
        margin_v = str(int(80 * scale_factor))
        highlight_tag = "{\\c&H00FFFF&\\3c&H00FFFF&}" # Text and outline to yellow

        
    # Group words into short phrases (max 24 characters or 0.6 seconds pause)
    phrases = []
    current_phrase = []
    current_char_count = 0
    
    for w in words:
        word_text = w["word"]
        word_len = len(word_text)
        
        if caption_style == "hormozi_pop":
            phrases.append([w])
            continue
            
        if not current_phrase:
            current_phrase.append(w)
            current_char_count = word_len
        elif current_char_count + 1 + word_len <= 24 and (w["start"] - current_phrase[-1]["end"] < 0.6):
            current_phrase.append(w)
            current_char_count += 1 + word_len
        else:
            phrases.append(current_phrase)
            current_phrase = [w]
            current_char_count = word_len
    if current_phrase:
        phrases.append(current_phrase)
        
    lines = [
        "[Script Info]",
        "; Script generated by Voice Sync Render Engine",
        "Title: Aligned Captions",
        "ScriptType: v4.00+",
        "WrapStyle: 0",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{font_name},{scaled_font_size},{primary_color},{secondary_color},{outline_color},{back_color},{bold},0,0,{border_style},{outline},{shadow},{alignment},10,10,{margin_v},1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    ]
    
    word_counter = 0
    for phrase in phrases:
        for idx, w in enumerate(phrase):
            # Extend highlight duration to the start of next word for seamless transition
            start_t = w["start"]
            end_t = phrase[idx+1]["start"] if idx < len(phrase) - 1 else w["end"]
            
            start_str = time_to_ass(start_t)
            end_str = time_to_ass(end_t)
            
            parts = []
            if caption_style == "hormozi_pop":
                colors = ["&H0000FFFF&", "&H0000FF00&", "&H00FFFFFF&"]
                color = colors[word_counter % len(colors)]
                anim_tag = "{\\fscx150\\fscy150\\t(0,150,\\fscx100\\fscy100)" + f"\\c{color}" + "}"
                parts.append(f"{anim_tag}{w['word'].upper()}{{\\r}}")
            else:
                for other_w in phrase:
                    if other_w == w and highlight_tag:
                        parts.append(f"{highlight_tag}{other_w['word']}{{\\r}}")
                    else:
                        parts.append(other_w['word'])
                        
            dialogue_text = " ".join(parts)
            lines.append(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{dialogue_text}")
            word_counter += 1
            
    with open(output_ass_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

def get_audio_duration(file_path: str) -> float:
    """Gets duration of audio file using ffprobe."""
    cmd = [
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", file_path
    ]
    try:
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True, timeout=60)
        return float(result.stdout.strip())
    except Exception as e:
        logger.error(f"Failed to probe audio duration for {file_path}: {e}")
    return 10.0

def get_video_dimensions(file_path: str) -> tuple[int, int]:
    """Gets width and height of video file using ffprobe."""
    cmd = [
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=width,height",
        "-of", "csv=s=x:p=0", file_path
    ]
    try:
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True, timeout=600)
        parts = result.stdout.strip().split('x')
        if len(parts) == 2:
            return int(parts[0]), int(parts[1])
    except Exception as e:
        logger.error(f"Failed to probe dimensions for {file_path}: {e}")
    return 640, 480

def escape_filter_path(path: str) -> str:
    """Helper to escape path for FFmpeg filter argument on Windows."""
    abs_path = os.path.abspath(path)
    escaped = abs_path.replace("\\", "/")
    escaped = escaped.replace(":", "\\:")
    escaped = escaped.replace("'", "'\\\\''")
    return escaped

@app.post("/render_video", response_model=RenderResponse)
async def render_video(request: RenderRequest):
    if not os.path.exists(request.synced_video_path):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Synced video file not found.")
        
    output_filename = f"{request.job_id}_final.mp4"
    output_path = os.path.join(OUTPUT_DIR, output_filename)
    
    # Retrieve original dimensions
    width, height = get_video_dimensions(request.synced_video_path)
    logger.info(f"Video detected dimensions: {width}x{height} (4K={width>=3840 or height>=3840})")
    
    cmd = [
        "ffmpeg", "-y",
        "-i", request.synced_video_path,
        "-i", request.audio_path,
    ]
    
    if request.bgm_path and os.path.exists(request.bgm_path):
        cmd.extend(["-i", request.bgm_path])
    
    video_filters = []
    
    # 1. Compile and Burn Subtitles if alignment metadata exists and caption style is not 'none'
    if request.caption_style and request.caption_style.lower() != "none" and request.alignment_path and os.path.exists(request.alignment_path):
        ass_filename = f"{request.job_id}.ass"
        ass_path = os.path.join(OUTPUT_DIR, ass_filename)
        logger.info(f"Generating ASS subtitles for job {request.job_id} at {ass_path}...")
        try:
            generate_ass_file(request.alignment_path, ass_path, request.caption_style, request.font_name, request.font_size, width, height)
            escaped_ass = escape_filter_path(ass_path)
            fonts_dir = os.path.abspath(os.path.join(STORAGE_DIR, "fonts"))
            escaped_fonts_dir = escape_filter_path(fonts_dir)
            video_filters.append(f"subtitles='{escaped_ass}':fontsdir='{escaped_fonts_dir}'")
        except Exception as e:
            logger.error(f"Failed to generate subtitle file: {e}")
            
    # 2. Draw watermark at bottom right - DISABLED as requested
    pass
        
    complex_filters = []
    
    if video_filters:
        complex_filters.append(f"[0:v]{','.join(video_filters)}[v_out]")
        map_v = "[v_out]"
    else:
        map_v = "0:v"
        
    # Apply studio vocal enhancement to stream 1:a (request.audio_path)
    voice_eq = "highpass=f=80,lowpass=f=12000,equalizer=f=3000:width_type=h:width=200:g=2"
    complex_filters.append(f"[1:a]{voice_eq}[voice_clean]")
    
    if request.bgm_path and os.path.exists(request.bgm_path):
        # 1. Apply volume parameter to BGM stream (which is input index 2:a)
        complex_filters.append(f"[2:a]volume={request.bgm_volume}[bgm_vol]")
        # 2. Sidechain compression ducking (BGM ducks automatically when voice is talking)
        complex_filters.append(f"[bgm_vol][voice_clean]sidechaincompress=threshold=0.12:ratio=4:attack=50:release=300[bgm_ducked]")
        # 3. Explicitly mix ducked BGM and pristine narration voice streams using amix filter (ends when narration ends)
        complex_filters.append(f"[voice_clean][bgm_ducked]amix=inputs=2:duration=first:dropout_transition=2[a_out]")
        map_a = "[a_out]"
    else:
        map_a = "[voice_clean]"
        
    if complex_filters:
        cmd.extend(["-filter_complex", ";".join(complex_filters)])
        
    cmd.extend(["-map", map_v, "-map", map_a])
    
    cmd.extend([
        "-c:v", "libx264",
        "-crf", "16",
        "-pix_fmt", "yuv420p",
        "-profile:v", "high",
        "-preset", "medium",
        "-c:a", "aac",
        "-b:a", "320k",
        "-movflags", "+faststart",
        "-progress", "-",
        output_path
    ])
    
    # Get total audio duration to scale progress percentage accurately
    total_dur = get_audio_duration(request.audio_path)
    
    logger.info(f"Rendering final video for job {request.job_id} using command: {' '.join(cmd)}")
    
    try:
        # Launch FFmpeg to read console progress line-by-line
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, bufsize=1)
        if request.job_id:
            active_processes[request.job_id] = p
        
        last_progress_sent = 70.0
        while True:
            if request.job_id and request.job_id in cancelled_jobs:
                raise Exception("Job cancelled by user")
            line = p.stdout.readline()
            if not line:
                break
                
            if "out_time_us=" in line:
                try:
                    time_us = int(line.split("=")[1].strip())
                    current_seconds = time_us / 1000000.0
                    
                    # Calculate percentage completed
                    progress_pct = (current_seconds / total_dur) if total_dur > 0 else 0
                    # Scale to fit rendering phase (70% to 95%)
                    scaled_progress = min(95.0, max(70.0, 70.0 + (progress_pct * 25.0)))
                    
                    if request.job_id and (scaled_progress - last_progress_sent >= 1.0 or scaled_progress == 95.0):
                        last_progress_sent = scaled_progress
                        # Send live callback to coordinator with short timeout to avoid distributed deadlocks
                        try:
                            requests.post(
                                f"http://127.0.0.1:8000/job/{request.job_id}/progress",
                                json={"status": "RENDERING", "progress": scaled_progress},
                                timeout=0.1
                            )
                        except Exception:
                            pass
                except Exception as ex:
                    logger.debug(f"Error parsing out_time_us: {ex}")
                    
        p.wait()
        if p.returncode != 0:
            if request.job_id and request.job_id in cancelled_jobs:
                raise Exception("Job cancelled by user")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="FFmpeg rendering failed during render."
            )
            
    except subprocess.TimeoutExpired:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="FFmpeg rendering timed out after 600 seconds."
        )
    except Exception as e:
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Rendering failed: {str(e)}"
        )
    finally:
        if request.job_id:
            active_processes.pop(request.job_id, None)
            cancelled_jobs.discard(request.job_id)
        
    return RenderResponse(
        status="success",
        output_video_path=os.path.abspath(output_path),
        details="Rendered H.264/AAC MP4 with word-highlighted ASS subtitles."
    )

@app.post("/cancel/{job_id}")
async def cancel_job(job_id: str):
    logger.info(f"Received cancel request for job {job_id}")
    cancelled_jobs.add(job_id)
    p = active_processes.get(job_id)
    if p:
        logger.info(f"Terminating active subprocess for job {job_id}")
        p.terminate()
        try:
            p.wait(timeout=1.0)
        except subprocess.TimeoutExpired:
            p.kill()
    return {"status": "ok"}

@app.get("/health")
def health():
    return {"status": "ok", "service": "render"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8003)
